spring:
  application:
    name: notification-service

server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---
spring:
  config:
    activate:
      on-profile: test

---
spring:
  config:
    activate:
      on-profile: prod
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
